id: P000616
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W20132
  title: རྒྱན་གྱི་བསྟན་བཅོས་དབྱངས་ཅན་ངག་གི་རོལ་མཚོ
  author: ''
  volumes:
    91eec18165164a95b4d30f487fecce08:
      image_group_id: I4849
      title: ''
      volume_number: 1
      total_pages: 790
      base_file: v001.txt
