id: I176D91D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T00:56:27+00:00'
last_modified: '2022-06-07T12:27:39.725110+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20132
  title: རྒྱན་གྱི་བསྟན་བཅོས་དབྱངས་ཅན་ངག་གི་རོལ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5778':
      image_group_id: I4849
      title: ''
      total_pages: 790
      order: 1
      base_file: 5778.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
